[package]
name = "ybc"
version = "0.1.0"
description = "A Yew component library based on the Bulma CSS framework."
authors = ["Anthony Dodd <dodd.anthonyjosiah@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/thedodd/ybc"
readme = "README.md"
categories = ["wasm", "web-programming"]
keywords = ["wasm", "web", "bulma", "css", "sass", "yew", "yew-components"]

[dependencies]
anyhow = "1"
derive_more = "0.99.9"
mixin = "0.2.0"
web-sys = { version="0.3", features=["Element", "File", "HtmlCollection", "HtmlSelectElement"] }
yew = { version="0.17.3", features=["web_sys"] }
yewtil = { version="0.3.2", features=["neq"] }
yew-router = { version="0.14.0", features=["web_sys"], optional=true }

[features]
default = ["router"]
router = ["yew-router"]
